# SPECIFIC OPTIONS OVERWRITTEN BY THIS THEME

# LOOKS
source = config/looks/decor.conf # Decoration (Blur, Rounding etc)
source = config/looks/animations.conf # Animations

general {
    border_size = 1
    col.active_border = $foregroundfull
}

decoration {
    rounding = 20

    blur {
        enabled = true
        size = 6
        passes = 4
    }
}

layerrule = match:namespace waybar, blur on
layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace rofi, blur on
layerrule = match:namespace swayosd, blur on

layerrule = match:namespace waybar, ignore_alpha 0.5
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5
layerrule = match:namespace rofi, ignore_alpha 0.5
layerrule = match:namespace swayosd, ignore_alpha 0.5
